/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTriangulationRouteImport } from './routes/_authenticated/triangulation'
import { Route as AuthenticatedThreatsRouteImport } from './routes/_authenticated/threats'
import { Route as AuthenticatedSocRouteImport } from './routes/_authenticated/soc'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityReportRouteImport } from './routes/_authenticated/security-report'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReconRouteImport } from './routes/_authenticated/recon'
import { Route as AuthenticatedNetworksRouteImport } from './routes/_authenticated/networks'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedAnalystRouteImport } from './routes/_authenticated/analyst'
import { Route as AuthenticatedActorsRouteImport } from './routes/_authenticated/actors'
import { Route as ApiPublicScanJobsRouteImport } from './routes/api/public/scan-jobs'
import { Route as ApiPublicNmapRouteImport } from './routes/api/public/nmap'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as AuthenticatedIncidentsIdRouteImport } from './routes/_authenticated/incidents.$id'
import { Route as AuthenticatedActorsIdRouteImport } from './routes/_authenticated/actors.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTriangulationRoute =
  AuthenticatedTriangulationRouteImport.update({
    id: '/triangulation',
    path: '/triangulation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedThreatsRoute = AuthenticatedThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSocRoute = AuthenticatedSocRouteImport.update({
  id: '/soc',
  path: '/soc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityReportRoute =
  AuthenticatedSecurityReportRouteImport.update({
    id: '/security-report',
    path: '/security-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReconRoute = AuthenticatedReconRouteImport.update({
  id: '/recon',
  path: '/recon',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNetworksRoute = AuthenticatedNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalystRoute = AuthenticatedAnalystRouteImport.update({
  id: '/analyst',
  path: '/analyst',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActorsRoute = AuthenticatedActorsRouteImport.update({
  id: '/actors',
  path: '/actors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicScanJobsRoute = ApiPublicScanJobsRouteImport.update({
  id: '/api/public/scan-jobs',
  path: '/api/public/scan-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNmapRoute = ApiPublicNmapRouteImport.update({
  id: '/api/public/nmap',
  path: '/api/public/nmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIncidentsIdRoute =
  AuthenticatedIncidentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedActorsIdRoute = AuthenticatedActorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedActorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actors': typeof AuthenticatedActorsRouteWithChildren
  '/analyst': typeof AuthenticatedAnalystRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/lab': typeof AuthenticatedLabRoute
  '/networks': typeof AuthenticatedNetworksRoute
  '/recon': typeof AuthenticatedReconRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security-report': typeof AuthenticatedSecurityReportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/soc': typeof AuthenticatedSocRoute
  '/threats': typeof AuthenticatedThreatsRoute
  '/triangulation': typeof AuthenticatedTriangulationRoute
  '/actors/$id': typeof AuthenticatedActorsIdRoute
  '/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/nmap': typeof ApiPublicNmapRoute
  '/api/public/scan-jobs': typeof ApiPublicScanJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actors': typeof AuthenticatedActorsRouteWithChildren
  '/analyst': typeof AuthenticatedAnalystRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/lab': typeof AuthenticatedLabRoute
  '/networks': typeof AuthenticatedNetworksRoute
  '/recon': typeof AuthenticatedReconRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security-report': typeof AuthenticatedSecurityReportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/soc': typeof AuthenticatedSocRoute
  '/threats': typeof AuthenticatedThreatsRoute
  '/triangulation': typeof AuthenticatedTriangulationRoute
  '/actors/$id': typeof AuthenticatedActorsIdRoute
  '/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/nmap': typeof ApiPublicNmapRoute
  '/api/public/scan-jobs': typeof ApiPublicScanJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/actors': typeof AuthenticatedActorsRouteWithChildren
  '/_authenticated/analyst': typeof AuthenticatedAnalystRoute
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/_authenticated/lab': typeof AuthenticatedLabRoute
  '/_authenticated/networks': typeof AuthenticatedNetworksRoute
  '/_authenticated/recon': typeof AuthenticatedReconRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/security-report': typeof AuthenticatedSecurityReportRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/soc': typeof AuthenticatedSocRoute
  '/_authenticated/threats': typeof AuthenticatedThreatsRoute
  '/_authenticated/triangulation': typeof AuthenticatedTriangulationRoute
  '/_authenticated/actors/$id': typeof AuthenticatedActorsIdRoute
  '/_authenticated/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/nmap': typeof ApiPublicNmapRoute
  '/api/public/scan-jobs': typeof ApiPublicScanJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/actors'
    | '/analyst'
    | '/assessment'
    | '/clients'
    | '/dashboard'
    | '/incidents'
    | '/lab'
    | '/networks'
    | '/recon'
    | '/reports'
    | '/security-report'
    | '/settings'
    | '/soc'
    | '/threats'
    | '/triangulation'
    | '/actors/$id'
    | '/incidents/$id'
    | '/api/public/ingest'
    | '/api/public/nmap'
    | '/api/public/scan-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/actors'
    | '/analyst'
    | '/assessment'
    | '/clients'
    | '/dashboard'
    | '/incidents'
    | '/lab'
    | '/networks'
    | '/recon'
    | '/reports'
    | '/security-report'
    | '/settings'
    | '/soc'
    | '/threats'
    | '/triangulation'
    | '/actors/$id'
    | '/incidents/$id'
    | '/api/public/ingest'
    | '/api/public/nmap'
    | '/api/public/scan-jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/actors'
    | '/_authenticated/analyst'
    | '/_authenticated/assessment'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/incidents'
    | '/_authenticated/lab'
    | '/_authenticated/networks'
    | '/_authenticated/recon'
    | '/_authenticated/reports'
    | '/_authenticated/security-report'
    | '/_authenticated/settings'
    | '/_authenticated/soc'
    | '/_authenticated/threats'
    | '/_authenticated/triangulation'
    | '/_authenticated/actors/$id'
    | '/_authenticated/incidents/$id'
    | '/api/public/ingest'
    | '/api/public/nmap'
    | '/api/public/scan-jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicNmapRoute: typeof ApiPublicNmapRoute
  ApiPublicScanJobsRoute: typeof ApiPublicScanJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/triangulation': {
      id: '/_authenticated/triangulation'
      path: '/triangulation'
      fullPath: '/triangulation'
      preLoaderRoute: typeof AuthenticatedTriangulationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/threats': {
      id: '/_authenticated/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof AuthenticatedThreatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/soc': {
      id: '/_authenticated/soc'
      path: '/soc'
      fullPath: '/soc'
      preLoaderRoute: typeof AuthenticatedSocRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security-report': {
      id: '/_authenticated/security-report'
      path: '/security-report'
      fullPath: '/security-report'
      preLoaderRoute: typeof AuthenticatedSecurityReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recon': {
      id: '/_authenticated/recon'
      path: '/recon'
      fullPath: '/recon'
      preLoaderRoute: typeof AuthenticatedReconRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks': {
      id: '/_authenticated/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof AuthenticatedNetworksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyst': {
      id: '/_authenticated/analyst'
      path: '/analyst'
      fullPath: '/analyst'
      preLoaderRoute: typeof AuthenticatedAnalystRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actors': {
      id: '/_authenticated/actors'
      path: '/actors'
      fullPath: '/actors'
      preLoaderRoute: typeof AuthenticatedActorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/scan-jobs': {
      id: '/api/public/scan-jobs'
      path: '/api/public/scan-jobs'
      fullPath: '/api/public/scan-jobs'
      preLoaderRoute: typeof ApiPublicScanJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nmap': {
      id: '/api/public/nmap'
      path: '/api/public/nmap'
      fullPath: '/api/public/nmap'
      preLoaderRoute: typeof ApiPublicNmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/incidents/$id': {
      id: '/_authenticated/incidents/$id'
      path: '/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AuthenticatedIncidentsIdRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/actors/$id': {
      id: '/_authenticated/actors/$id'
      path: '/$id'
      fullPath: '/actors/$id'
      preLoaderRoute: typeof AuthenticatedActorsIdRouteImport
      parentRoute: typeof AuthenticatedActorsRoute
    }
  }
}

interface AuthenticatedActorsRouteChildren {
  AuthenticatedActorsIdRoute: typeof AuthenticatedActorsIdRoute
}

const AuthenticatedActorsRouteChildren: AuthenticatedActorsRouteChildren = {
  AuthenticatedActorsIdRoute: AuthenticatedActorsIdRoute,
}

const AuthenticatedActorsRouteWithChildren =
  AuthenticatedActorsRoute._addFileChildren(AuthenticatedActorsRouteChildren)

interface AuthenticatedIncidentsRouteChildren {
  AuthenticatedIncidentsIdRoute: typeof AuthenticatedIncidentsIdRoute
}

const AuthenticatedIncidentsRouteChildren: AuthenticatedIncidentsRouteChildren =
  {
    AuthenticatedIncidentsIdRoute: AuthenticatedIncidentsIdRoute,
  }

const AuthenticatedIncidentsRouteWithChildren =
  AuthenticatedIncidentsRoute._addFileChildren(
    AuthenticatedIncidentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActorsRoute: typeof AuthenticatedActorsRouteWithChildren
  AuthenticatedAnalystRoute: typeof AuthenticatedAnalystRoute
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRouteWithChildren
  AuthenticatedLabRoute: typeof AuthenticatedLabRoute
  AuthenticatedNetworksRoute: typeof AuthenticatedNetworksRoute
  AuthenticatedReconRoute: typeof AuthenticatedReconRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSecurityReportRoute: typeof AuthenticatedSecurityReportRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSocRoute: typeof AuthenticatedSocRoute
  AuthenticatedThreatsRoute: typeof AuthenticatedThreatsRoute
  AuthenticatedTriangulationRoute: typeof AuthenticatedTriangulationRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActorsRoute: AuthenticatedActorsRouteWithChildren,
  AuthenticatedAnalystRoute: AuthenticatedAnalystRoute,
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRouteWithChildren,
  AuthenticatedLabRoute: AuthenticatedLabRoute,
  AuthenticatedNetworksRoute: AuthenticatedNetworksRoute,
  AuthenticatedReconRoute: AuthenticatedReconRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSecurityReportRoute: AuthenticatedSecurityReportRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSocRoute: AuthenticatedSocRoute,
  AuthenticatedThreatsRoute: AuthenticatedThreatsRoute,
  AuthenticatedTriangulationRoute: AuthenticatedTriangulationRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicNmapRoute: ApiPublicNmapRoute,
  ApiPublicScanJobsRoute: ApiPublicScanJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
